platform :ios, '8.0'
use_frameworks!

xcodeproj '/Users/alvar/git/temadagar-ios/Temadagar.xcodeproject/'

target 'Temadagar' do
pod 'SwiftyJSON'
pod 'ImageLoader'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire'
end