platform :ios, ‘9.0’
use_frameworks!

xcodeproj '/Users/alvar-mac/git/temadagar-ios/Temadagar.xcodeproj/'

target 'Temadagar' do
pod 'SwiftyJSON'
pod 'ImageLoader'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire'
end